---
apiVersion: v1
kind: Service
metadata:
  name: articlearenadb
  labels:
    app: articlearenadb
spec:
  clusterIP: None
  selector:
    app: articlearenadb
  ports:
    - name: tcp
      protocol: TCP
      port: 3306
