---
apiVersion: v1
kind: Service
metadata:
  name: backend-server-article-arena-svc
spec:
  selector:
    app: backend-server-article-arena
  type: NodePort
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30006
